### ISSUE TITLE
Support dynamic forms with form field data population

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/form-js#200]
> **This is an epic issue that may be broken down into multiple tasks if needed**

__What should we do?__

Our users (e.g. SUPPORT-12025) require forms to be created dynamically based on input data, for example depending on a category, display specific form fields. Dynamic forms allow you to automatically create form fields and layouts based on ingesting data from any source.

This does not mean that we're going to add data transformation capabilities in form-js (as of now). The library itself only provides a simple in-out API to provide the necessary data and pipe it out afterward.

*Prerequisites*

Cf. [Research Miro Board](https://miro.com/app/board/uXjVO7qaIIw=/)

- [x] Research
	- [x] Create an understanding of what `form-js` currently delivers, and what it currently doesn't deliver (from the data schema perspective) 
	- [x] Identify dependencies (e.g. Tasklist(s)), what do we need to lint? How do they handle data?
- [x] Decisions
	- [x] Do we integrate `form-js-playground` into Camunda Modeler 👍 
	- [x] Do we scope another, more scalable multi-select component? (cf. https://github.com/bpmn-io/form-js/issues/198) 👍 
	- [x] Do we want to include the non-selected values in our output data for multiselect (and potentially singleselect)? 👎 

*Breakdown*

- [x] ~https://github.com/bpmn-io/internal-docs/issues/527~ --> This will be handled in a separate epic. 
- [x] https://github.com/bpmn-io/form-js/issues/249
- [x] https://github.com/bpmn-io/internal-docs/issues/529
- [x] https://github.com/bpmn-io/form-js/issues/196
- [x] https://github.com/bpmn-io/form-js/issues/198
- [x] https://github.com/bpmn-io/form-js/issues/197
- [x] https://github.com/bpmn-io/form-js/issues/256
- [x] Discuss with Tasklist C7 team if we can drop: https://github.com/bpmn-io/form-js/issues/103 and instead provide the entire variable scope to forms (as is done for C8)
- [x] [Release alpha version of form-js](https://github.com/bpmn-io/form-js/pull/282) --> `@bpmn-io/form-js@0.8.0-alpha.0`

*Other topics (related and follow up, but not in the scope of this epic)*

- https://github.com/bpmn-io/form-js/issues/4
- https://github.com/bpmn-io/form-js/issues/247
- Support dynamic labels (e.g., via template literals) SUPPORT-12609
- Allow setting default values for multiselects. 
	- We've decided to drop this as part of this epic because it would require building another multi-select component for the properties panel, which currently seems to high effort for the functionality (@christian-konrad , @Skaiir , @MaxTru)

__Why should we do it?__

Be able to create forms dynamically on given data.

Context: https://github.com/camunda/product-hub/issues/55 
Cf. [Value Proposition](https://docs.google.com/presentation/d/15tjO2EuBqXlNf6vx6bZtIBWiyTBvHGXdON-0EJEfy7M/edit#slide=id.gfbb0d5d7fc_0_81)
Cf. https://jira.camunda.com/browse/SUPPORT-12025

**Comment by MaxTru** [comment]
Comment from @marstamm in Modeler Weekly:
* Note that input-data in camunda-platform land does not provide `array` / `list` data type. Hence the dynamic creation of multiple values in a multi-element component might be difficult to implement for camunda-platform.

Comment from @nikku in Modeler Weekly in response:
* In camunda-cloud, this limtation is not given. There the data is basically any JSON style data, which would fit well.

**Comment by marstamm** [comment]
## Possible Platform integration
The Platform also supports a `json` variable type. The JSON is delivered Stringified from the API and has to be parsed in the frontend. See this example of a variable result from the backend:
<details>
<summary>JSON</summary>

```Json
{
  "VariableA": {
    "type": "Json",
    "value": "[\n{\"a\": 1},\n{\"b\": 2}\n]",
    "valueInfo": {}
  },
  "VariableB": {
    "type": "Integer",
    "value": 1234,
    "valueInfo": {}
  }
}
```
</details>

We can use the "Json" type to create lists and use them in the form. Keep in mind that:
- We need documentation in the platform docs for the Structure required by form-js
- We would parse **all** JSON variables to Objects before passing it to form-js. With this setup, we could not support use-cases like editing raw-JSON in an text area anymore.
- The returned values need to be annotated before being submitted to the backend. This can be done in Tasklist if the form-js return value is an array/object

**Comment by pinussilvestrus** [comment]
Sync of next working steps (@Skaiir @pinussilvestrus)
* We have this board to sketch around open topics: https://miro.com/app/board/uXjVO7qaIIw=/
* We updated this epic issue to collect open questions
* @Skaiir will continue on the multi-select checkbox (https://github.com/bpmn-io/form-js/issues/196)
* @pinussilvestrus will spike around the form-js-playground integration (https://github.com/bpmn-io/internal-docs/issues/527)
* @Skaiir and @pinussilvestrus will conduct a kickoff with the team (probably next Friday) to clarify open questions and create a shared understanding

**Comment by Skaiir** [comment]
Just had a chat with @vsgoulart who is our link to C8 tasklist and had some pretty valuable takeaways from it.

- Data formats in C8 aren't really a concern, as we initially thought. It's generic JSON and inputs and outputs will just work.
- Variable passing on the other hand isn't as automatic, because some diagrams are huge they cannot just blindly feed all the variables into the forms, so they determine which variables to provide based on the form schema
  - this sucks for them, because every change to the schema will result to a backend change
  - this also sucks for us, because that means we're dependent on backend changes to improve forms, which will lead to development overheads and generally we don't fully own this, but we could
  - the solution here is this ticket: https://github.com/bpmn-io/form-js/issues/103, we could provide the variables that need to be imported ourselves through some kind of a function we expose to them. Implementing this would let us upgrade form-js in the future without ever having to involve backend (at least for C8)
  
__Following discussion:__
Implementing this ticket just feels like a no-brainer and everybody's agreed so far, so I've adopted this into the scope of dynamic forms.

**Comment by Skaiir** [comment]
Insights from C7 tasklist by @tasso

- The utility discussed for C8 would also work and is appreciated, unlike C8, C7 actually feeds all the data in the variable scope to the form. Upgrades to this would make sense along the development of that util.
- For multiselect, we may want to store the data as objects with string / boolean pairs instead of string arrays, the reason for that is that, when defining the options statically on the form, the process will not be aware of them. true | false | undefined  gives a process developer more choice. 
  - Example scenario: A multi checkbox with 10 different emails, we select 3 of those, those 3 get an in depth email about some process information, the 7 others only get a quick summary. If those were defined in the form options, the process scope is not aware of it, and hence we'd need to output the falsy selection as well to create the above described behavior.
- A little aside related to the previous point, the fact that we don't output falsy values for most of our single select controls could also be considered a limitation.
- The only feasible way of doing all this is via JSON object definitions, this would require some changes in C7 tasklist to at least handle transforming JSON object definitions from Tasklist to a JSON object literal fed to form-js inputs, and back from form-js outputs into an object definition. Right now the code doesn't do that: https://github.com/camunda/camunda-bpm-platform/blob/master/webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js#L56-L92.

**Comment by nikku** [comment]
> A little aside related to the previous point, the fact that we don't output falsy values for most of our single select controls could also be considered a limitation.

Don't we? Can you share an example we can dive into?

**Comment by Skaiir** [comment]
Well, perhaps we're not understanding eachother but the point that was raised is that the selectable values defined statically inside of the form is lost to the process. A radio button is a singleselect. We don't output information about the options which were not selected. This just ties in with the point right before and is something Tassilo brought up. That information is restricted to our form and there's no way to access it from the process down the line.

**Comment by nikku** [comment]
> Example scenario: A multi checkbox with 10 different emails, we select 3 of those, those 3 get an in depth email about some process information, the 7 others only get a quick summary. If those were defined in the form options, the process scope is not aware of it, and hence we'd need to output the falsy selection as well to create the above described behavior.

For this example (which relates to falsy values) I'd argue that 

(1) a list of `X` emails is a process variable (or otherwise hardcoded engine binding); we'll support mapping such dynamic variable to selects
(2) returning only what is selected is safe, as on the engine level we can diff between what is being returned from the form and what has previously been fetched

Again, I may miss-understand something. In that case it could be best to actually model such scenario, ensure we all understand it, and carefully decide if we want to change existing semantics (start to submit falsy stuff).

**Comment by Skaiir** [comment]
Is there a way to do (2) if the data isn't fetched but hardcoded into the form?

**Comment by nikku** [comment]
But yea, if multi-select becomes a dedicated, new component (not the same as a check-box) we can be more creative with submit behaviors.

> Is there a way to do (2) if the data isn't fetched but hardcoded into the form?

We could add the ability to submit additional static configuration with the form. That would be one resolution.

Like: Always submit `emailUsers = [ {  name, value=email } ]` and `selectedEmailUsers=[...]`.

---

It may be worth discussing how far we want to go with static bindings, and also what to consciously not support for improved happiness of the 80%.

**Comment by Skaiir** [comment]
Agreed, the point only related to static definitions anyways. I agree completely that if you've got your data source as a process variable there's no argument there we wouldn't need it. Cool, we'll chat about it during the Kickoff.

**Comment by felix-mueller** [comment]
Hi there

I got a support feature request (https://jira.camunda.com/browse/SUPPORT-12403) where a user is asking about support for:

Given: 
`{
"schemaVersion": 2,
"exporter":
{ "name": "form-js (https://demo.bpmn.io)", "version": "0.1.0" }
,
"components": [
{
"text": "# File an Invoice\n\nAdd your invoice details below.\n\nCustomer Id: ${customerId}",
"type": "text",
"id": "Field_1m5gj8s"
},
{ "action": "submit", "key": "submit", "label": "Submit", "type": "button", "id": "Field_03qrh3a" }
],
"type": "default",
"id": "Form_1ef51ca"
}
  `

Where ${customerId} get's replaced by the process variables

Is this in scope of this ticket here?

**Comment by nikku** [comment]
No it is not, it is related to https://github.com/bpmn-io/form-js/issues/247 and I've linked the support case there.

**Comment by felix-mueller** [comment]
Thank you for the quick reply!

**Comment by pinussilvestrus** [comment]
Thanks for sharing, I also added it to the "other topics" section above (not in this epic, but as a follow-up) 👍

**Comment by Skaiir** [comment]
@nikku We're going to bring FEEL into forms, and this looks like that would fit such an implementation as well. I think this could be taken on as part of the conditional rendering epic here: https://github.com/camunda/product-hub/issues/56.

**Comment by Skaiir** [comment]
Next release will be October the 11th, which gives us a timeline of 5.5 months for these changes to be completed.

**Comment by dfulgham** [comment]
Why wouldn't dynamic input data just be created prior to instantiating the form, passing a function into the form as input data would be considerably harder to control for security reasons, making it easy to inject malicious code?

Unless you are suggesting to allow the function to access internal form data, for example to accomplish cascading selects, one select determines the values of the next.  We would then have some default params passed to the the functions like formData etc.

``` 
inputData = {
  countryValues: [{label:"Canada",key:"CA"}, {"label":"Germany","key":"DE"}, ...],
  citiesValues: async function(formData){ 
     const {country} = formData;
     const cities = await fetch(...);
     return cities.filter(c => { return c.country === country}).map(c => {
       return { label: c.name, value: c.key }
    })
   },
...
}
```

triggering all functions run when formData changes somehow, and also trigger a loading indicator when the promise is waiting to resolve would be advantageous.

This would be cool, but concerns of security issues remain.

**Comment by dfulgham** [comment]
> > Example scenario: A multi checkbox with 10 different emails, we select 3 of those, those 3 get an in depth email about some process information, the 7 others only get a quick summary. If those were defined in the form options, the process scope is not aware of it, and hence we'd need to output the falsy selection as well to create the above described behavior.
> 
> For this example (which relates to falsy values) I'd argue that
> 
> (1) a list of `X` emails is a process variable (or otherwise hardcoded engine binding); we'll support mapping such dynamic process variables to selects options (2) returning only what is selected is safe, as at run-time can diff between what is being returned from the form and what has previously been fetched
> 
> Again, I may miss-understand something. In that case it could be best to actually model such scenario, ensure we all understand it, and carefully decide if we want to change existing semantics (start to submit falsy stuff).

Wouldn't it just be better to handle that in the process, the process would have the initial list of email and now the selected few.  by removing the selected emails from the full list process variable and store it in a filtered process variable list in the process and then send summary emails to those, and detailed emails to the selected values.  No other form select works by submitting not selected values.

**Comment by dfulgham** [comment]
> Well, perhaps we're not understanding eachother but the point that was raised is that the selectable values defined statically inside of the form is lost to the process. A radio button is a singleselect. We don't output information about the options which were not selected. This just ties in with the point right before and is something Tassilo brought up. That information is restricted to our form and there's no way to access it from the process down the line.

I think a better way of passing data from input to output would be to create a hidden type form component, this way you could pass any value from the input to the output if required.  This would be in line with how a regular web form would pass data that doesn't require user interaction.

**Comment by dfulgham** [comment]
> 

Could we create an option in the form schema to provide a preSubmit function that could arbitrarily structure the submitted data any way the developer would like prior to form submission?  Passing this function the formData, InputData, and perhaps components

**Comment by nikku** [comment]
> https://github.com/bpmn-io/form-js/issues/200#issuecomment-1123170808

@dfulgham This is what we settled on (@pinussilvestrus @Skaiir please confirm).

> https://github.com/bpmn-io/form-js/issues/200#issuecomment-1123167429

@dfulgham Exactly. We'll not persue this direction (@pinussilvestrus @Skaiir please confirm).

Generally speaking we shall not re-invent the web, but rather build in the spirit of existing web forms (including hidden inputs you mentioned for secret data passing). This is what we do to date, this is what we'll do in the future.

**Comment by nikku** [comment]
> Could we create an option in the form schema to provide a preSubmit function that could arbitrarily structure the submitted data any way the developer would like prior to form submission? 

What would be the dedicated use-case? As you mentioned I can absolutely wrap the form and do whatever I want before import, and after submit.

**Comment by nikku** [comment]
> Why wouldn't dynamic input data just be created prior to instantiating the form (https://github.com/bpmn-io/form-js/issues/200#issuecomment-1123160041)

The sole reason for passing a function would be to allow dynamic lookup, i.e. when huge amounts of data exist that cannot be pre-loaded (i.e. list of emails to auto-complete). In this case you can provide a lookup function. 

The default use-case for our dynamic form works is indeed that data (and options) are dynamically populated via input variables, however just-in-time lookup is one of the options we see with popular multi-select libraries, i.e. [select2](https://select2.org/#remote-data-support).

**Comment by dfulgham** [comment]
> What would be the dedicated use-case? As you mentioned I can absolutely wrap the form and do whatever I want before import, and after submit.

It was for the use case where the developer wanted access to the Component Elements (i.e. statically set value lists) and the Input values at time of submission (i.e. in the case of fetched data). 

Just brainstorming ways to accommodate the use case put forward by you @nikku but I think these could also be enabled with the hidden component type, allowing the input data at time of submission to be submitted.  And I don't personally think I would use the case of needing any statically set values, if I needed them i'd rather set those values with an input value dynamically.

**Comment by dfulgham** [comment]
> > Why wouldn't dynamic input data just be created prior to instantiating the form ([#200 (comment)](https://github.com/bpmn-io/form-js/issues/200#issuecomment-1123160041))
> 
> The sole reason for passing a function would be to allow dynamic lookup, i.e. when huge amounts of data exist that cannot be pre-loaded (i.e. list of emails to auto-complete). In this case you can provide a lookup function.
> 
> The default use-case for our dynamic form works is indeed that data (and options) are dynamically populated via input variables, however just-in-time lookup is one of the options we see with popular multi-select libraries, i.e. [select2](https://select2.org/#remote-data-support).

Yes, i worked my way to this understanding too while providing the example of [cascaded selects](https://github.com/bpmn-io/form-js/issues/200#issuecomment-1123160041)

**Comment by pinussilvestrus** [comment]
> > But yea, if multi-select becomes a dedicated, new component (not the same as a check-box) we can be more creative with submit behaviors.
> > > Is there a way to do (2) if the data isn't fetched but hardcoded into the form?
> > 
> > 
> > We could add the ability to submit additional static configuration with the form. That would be one resolution.
> > Like: Always submit `emailUsers = [ { name, value=email } ]` and `selectedEmailUsers=[...]`.
> > It may be worth discussing how far we want to go with static bindings, and also what to consciously not support for improved happiness of the 80%.
> 
> Could we create an option in the form schema to provide a preSubmit function that could arbitrarily structure the submitted data any way the developer would like prior to form submission? Passing this function the formData, InputData, and perhaps components

That could deserve [an extra issue](https://github.com/bpmn-io/form-js/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.md) (if not already existing). Feel free to open one and we can discover this particular use case over there 👍

**Comment by Skaiir** [comment]
> I think a better way of passing data from input to output would be to create a hidden type form component (https://github.com/bpmn-io/form-js/issues/200#issuecomment-1123170808)

> @dfulgham This is what we settled on (@pinussilvestrus @Skaiir please confirm).

I wouldn't say we settled on anything as part of this epic with regards to passing data. In the end this raises questions about how we differentiate 'form' scope from 'input' scope, and this all will play into conditional rendering, FEEL, which are later epics for this and hence we'll defer the particular data passing case to then.

A hidden form component to do mappings would be a good way to handle this case though, so would pre-submit actions. These are both good brainstorms and we'll consider them both.

**Comment by Skaiir** [comment]
Following a sync, I'll provide a little bit of summary / context for @currandwyer :

___

Current icon set in use

![image](https://user-images.githubusercontent.com/17801113/169854610-0aec8491-5cee-4d4c-a7a7-c8f8a4790432.png)

text field - number - checkbox (individual) - radio (multiple)
select - text (supports markdown and basic html) - button

We also have some unused icons. 
Here is the whole collection: [Form icons.zip](https://github.com/bpmn-io/form-js/files/8756292/Form.icons.zip)

___

The icons which are blocking progress currently are:

- Checklist
- Taglist

___

Some icons we **_might_** want to implement in the future would be:

- Datetime picker
- Combo-box (similar to a select, but searchable)
- Image view
- Floating point number fields (while we already have a numbers field for integers, the icon for it is a bit integer-specific as well)
- Fieldset 
- Render-group (similar to a field set, but with no visual component, used for conditional rendering)

Note that at this stage, we are very early in defining the requirements. Some icons will not make it, some are redundant and we might opt for a configuration option instead. These are only for context and we're not looking to produce them yet.

A library contributor has provided their implementation of a Fieldset icon already, I've provided it in the attached collection , if you think it's satisfactory, we can use that straight away. This is not within the scope but I'd love bit of feedback on it 😄.

___

More context:

[Discussion thread on the Taglist](https://github.com/bpmn-io/form-js/issues/198)
[The issue regarding the new basic fields](https://github.com/camunda/product-hub/issues/97)

**Comment by pinussilvestrus** [comment]
One update [regarding the breakdown](https://github.com/bpmn-io/form-js/issues/200#issue-1048446470): We will handle the [form-js-playground integration](https://github.com/bpmn-io/internal-docs/issues/527) separately, as it does not only depend on dynamic data anymore.

**Comment by Skaiir** [comment]
For visibility, tracking, linting and documentation concerns have moved over to https://github.com/bpmn-io/internal-docs/issues/596. We will now handle these things as part of release instead of continuously, as it reduces overheads and makes it easier for us to work with our various integrations.

Related:
https://github.com/bpmn-io/internal-docs/issues/597

**Comment by nikku** [comment]
> We will now handle these things as part of release instead of continuously, as it reduces overheads and makes it easier for us to work with our various integrations.

When did we decide this? And who decided it?

**Comment by Skaiir** [comment]
@nikku 

This was initially in agreement with myself and @pinussilvestrus. We pitched this internally and @CatalinaMoisuc understands where we're coming from as well. If you want to clarify what it's all about we can have a chat.

**Comment by CatalinaMoisuc** [comment]
@Skaiir see also my comment here: https://github.com/bpmn-io/internal-docs/issues/597#issuecomment-1188693392.

Also, what I agreed on is that it makes sense to wait with i.e. the tracking and documentation until we clarify with Tasklist their requirements. Your argument in that favour was that: we might need to change implementation for being able to integrate with Tasklist so it makes sense to wait so we don't have to make changes i.e. rewrite the docs.

See below:
> To recap and make sure we are on the same page, until Tasklist is ready for these changes you plan to:
> * prepare the implementation to make it compatible with Tasklist (when your contact persons from Tasklist are back)
> * implement potential changes required by Tasklist (when your contact persons from Tasklist are back)
> * prepare docs (depends on the integration with Tasklist - the previous two bullet points - so has to be done after potential changes are implemented)
> * clarify what we should track and prepare that (doesn't have any dependencies, can just me done)
> And once we have the Tasklist release, we do integration testing and prepare that to release in Modeler.

Now given that @nikku mentioned that Tasklist is also releasing alphas monthly then we don't actually have to wait until October and moreover, if we agree on the approach to take with `camunda-form-js` in #597, we might even want to release earlier.

**Comment by pinussilvestrus** [comment]
I wouldn't worry too much about implementation requirements change now, as we clarified the API beforehand in discussions with the respective teams. 

I think the point here is that we should not feel blocked in closing epics because we have to wait for certain activities that need at least final confirmation (linting, tracking, as mentioned above). These things can be handled in a separate manner (e.g. via a [integration tracking issue](https://github.com/bpmn-io/internal-docs/issues/596)).

However, I also agree we have the initiative we are trying to roll on (cf. https://github.com/bpmn-io/internal-docs/issues/597#issuecomment-1188693392). We should all agree as a team on the best approach, also including our users (our product teams).

**Comment by CatalinaMoisuc** [comment]
### Notes for today's(21.07.2022) meeting: `Discuss development & integration strategy for `form-js` features`

**Note that**:

- In bpmn.js we use linting for detecting incompatibilities between Modeling and the execution platform. For instance: Connectors are only supported as of 8.0 and use a linting rule to highlight the incompatibility when an older execution platform is used

- There are monthly alpha releases in Camunda Platform 8. The customer can create a cluster and choose channels alpha and choose the version i.e. Zeebe-8.1.0-alpha1

- There is no linting available in Web Modeler for forms, furthermore, the feature only exists in camunda-modeler library

**Next steps**:

- Draw the dependencies and how this feature can work end to end and highlight the implications for Web Modeler and Tasklist

- Make linting available also in Web Modeler - pull it out of the camunda-modeler

- Integrate linting in Web Modeler

- Allow selection of execution platform in form-js as well

- Add linting rule to ensure that for older execution platforms that do not support these new properties are warned that the feature is not available

- Agree on when this linting rule and the new form-js makes sense to be released in Web Modeler (depends on Tasklist alpha releases)

- Discover how gracefully Tasklist handles the incompatibilities in case one user wants to deploy an incompatibile form feature to an older Tasklist version

**Comment by CatalinaMoisuc** [comment]
As discussed, @Skaiir as the DRI, please make sure you open issues for the next steps and make the dependencies transparent in this epic.
