### ISSUE TITLE
[Implement Tracking] Enable FEEL and Templating for more properties

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#587]
> This is the implementation epic for https://github.com/camunda/product-hub/issues/722

### What should we do?

We have just successfully integrated the feelers syntax in the text component text property in 8.2. We want to now convert over a few properties in the application to accept this syntax or simply FEEL expressions. 

This includes

> This needs to be broken down properly

- [x] [Support `readonly`](https://github.com/bpmn-io/form-js/issues/396)
- [x] https://github.com/bpmn-io/form-js/issues/639
- [x] https://github.com/bpmn-io/properties-panel/issues/240
- [x] https://github.com/bpmn-io/properties-panel/issues/194
- [x] https://github.com/bpmn-io/form-js/issues/653
- [x] Ensure `getSchemaVariables` utilities are updated
- [x] Clarify breaking changes (if any)
- [x] https://github.com/camunda/form-linting/issues/52
- [x] Ensure schema version is updated
- [x] https://github.com/camunda/team-hto/issues/247
- [x] Integrate updates into products
  - [x] Tasklist
    - [x] add dev data for readonly
    - [x] add dev data for more expressions 
  - [x] Desktop Modeler
  - [x] Web Modeler
- [ ] Spread the word

### Why should we do it?

Change the behavior of your form reactively via simple rules, based on the context provided by process variables and other form input. 

We have the technical capabilities in place, now let's enable it.

### Additional context

Related to https://github.com/camunda/product-hub/issues/722
Related to this, and tightly coupled: https://github.com/camunda/product-hub/issues/918. It makes sense to start on this in parallel, to have the proper support of FEEL in `readonly`
Miro: https://miro.com/app/board/uXjVMMtnox0=/

**Comment by pinussilvestrus** [comment]
A user mentioning `disabled` as needed for FEEL: https://github.com/camunda/camunda-modeler/issues/3600

**Comment by pinussilvestrus** [comment]
### Kickoff results

https://miro.com/app/board/uXjVMMtnox0=/

- We consider use feelers for all feel optional string fields  
- We do not support FEEL for disabled  
- We consider a standalone docs page about templating (not only in text views)  
- @pinussilvestrus to clarify with @RomanKostka  and @christian-konrad: really no tracking?  
- Follow up: initiate for BPMN properties (e.g. task title)  
- Discuss discouraging disabled fields  (cf. https://github.com/bpmn-io/form-js/issues/362)
- @pinussilvestrus to clarify with @RomanKostka: how do we indicate feelers fields?

**Comment by pinussilvestrus** [comment]
Implementation is done and released via form-js@1.0.0-alpha.10, basically waiting for the next release cycle for integration into Tasklist and the Modelers.
