### ISSUE TITLE
Implement tracking module examples & extension points

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#648]
> Tracking will not be implemented at the repo level (and never will be), we are just talking about extension points. 

### Is your feature request related to a problem? Please describe.

Some products using form-js may want to be able to start tracking certain features in a more refined manner. At the moment, we have nothing to hook into which could be used for this purpose. Hence, as a start, it would be nice to have example usages, and perhaps a few tests to start playing around with tracking events. 

### Describe the solution you'd like

While tracking should be done on the implementation side, we need to already outline the structure of how such tracking events are sent. To achieve this, we would set up: 

- [ ] some example tracking points
- [ ] an example tracking module used in tests
- [ ] documentation on how to implement your own tracking

### Describe alternatives you've considered

-

### Additional context

This is mainly a Camunda purpose for our products, but other users of our libraries may be interested to hook in their own tracking implementations as well.

**Comment by Skaiir** [comment]
This doesn't make much sense actually, we can simply define events on the eventbus for this purpose and track whatever is needed. Feel free to re-open if you think this warrants a bespoke solution. For now events are definitely enough, perhaps I'm not seeing a future scenario.
