### ISSUE TITLE
Create properties panels for the table component

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#890]
### TODO

- [ ] Add section `General`, with the following fields:
   - [ ] `Table header`: optional, type text, FEEL toggable
   - [ ] `Data source`: required, type text, FEEL toggable
   - [ ] `Default number of rows`: required, type number, greater than 0, default value 10
   - [ ] `Pagination`: required, toggle, enabled by default
- [ ] Add section `Columns`, FEEL toggable, list of objects `header` and `context key`

### Additional information
- [Figma link](https://www.figma.com/file/J78Djf3PgCEAPxFD86floX/Form-Editor-Components?type=design&node-id=290-68794&mode=design&t=0dXyhVaRNNXSJBTH-0)

**Comment by marcosgvieira** [comment]
@vsgoulart I'm moving this to Needs Review as we have https://github.com/bpmn-io/form-js/pull/912 for this. Please move it back if this is not the right state.
