### ISSUE TITLE
Add table component to the editor

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#891]
### TODO

- [ ] Add new table component to the palette under the `Presentation` section
- [ ] The table component should render only 1 row on the editor panel
- [ ] When we add a new table component a new field should be created in the sample context with mock data to populate the table in the viewer

### Additional information
- [Figma link](https://www.figma.com/file/J78Djf3PgCEAPxFD86floX/Form-Editor-Components?type=design&node-id=290-68794&mode=design&t=0dXyhVaRNNXSJBTH-0)
